version: "3"
services:
  nginx: 
    image: nginx:latest
    container_name: ${PROJECT_NAME}_nginx
    volumes:
      - ./nginx/confs:/etc/nginx/conf.d
      - ./html:/var/www/html/     
    ports:
      - "80:80"
      - "3030:3030"
      - "8025:8025"
    depends_on: 
          - php7.4-laravel

  php7.4-laravel:
    build: ./php7.4-laravel
    container_name: ${PROJECT_NAME}_php7.4-laravel
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_URL: "http://localhost"

      DB_CONNECTION: mysql
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_HOST: ${MYSQL_HOST}
      DB_PORT: ${MYSQL_PORT}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}

      BROADCAST_DRIVER: log
      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}

      MAIL_MAILER: smtp
      MAIL_HOST: ${MAILHOG_HOST}
      MAIL_PORT: 2525
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null
      MAIL_FROM_ADDRESS: null
    volumes:
      - ./html:/var/www/html/     
    depends_on:
      - redis6.0
      - mailhog 
      - mysql-8

  redis6.0:
    image: redis:6.0.6-buster
    container_name: ${REDIS_HOST}
    command: ["redis-server", "--appendonly", "yes"]

  mysql-8:
    image: mysql:8
    container_name: ${MYSQL_HOST}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  
  mailhog:
    image: mailhog/mailhog
    container_name: ${MAILHOG_HOST}
    expose:
      - 1025
      - 8025